config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/show'
  get 'articles/edit'
  get 'articles/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<div class="container m-4">
  <div>
    <h1>Articles</h1>
  </div>
  <div>
    <ul class="list-group">
    <% @articles.each_with_index do |article, index| %>
      <li class="list-group-item border border-0">
        <div class="card">
          <div class="card-header d-flex justify-content-between">
            <%= article.title %>
            <%= link_to "details", article_path(article) %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= article.content %></p>
          </div>
        </div>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<div class="container m-5">
  <div class="card">
    <h5 class="card-header"><%= @article.title %></h5>
    <div class="card-body">
      <p class="card-text"><%= @article.content %></p>
      <div class="d-flex justify-content-end">
        <button class="btn btn-outline-primary m-2"><%= link_to "edit", edit_article_path(@article) %></button>
        <button class="btn btn-outline-primary m-2"><%= link_to "delete", edit_article_path(@article) %></button>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <%= link_to "Back to list", articles_index_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>